<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.astro</groupId>
    <artifactId>2025-test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.nuxeo.runtime</groupId>
            <artifactId>nuxeo-runtime</artifactId>
            <version>10.10</version>
        </dependency>
        <dependency>
            <groupId>org.nuxeo.ecm.core</groupId>
            <artifactId>nuxeo-core</artifactId>
            <version>10.10</version>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <id>nuxeo-public</id>
            <url>https://maven.nuxeo.org/nexus/content/repositories/public/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>nuxeo-maven-snapshots</id>
            <url>https://maven.nuxeo.org/nexus/content/repositories/public-snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>nuxeo-private</id>
            <url>https://maven.nuxeo.org/nexus/content/repositories/private/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>nuxeo-studio</id>
            <url>https://connect.nuxeo.com/nuxeo/site/studio/maven</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <updatePolicy>always</updatePolicy>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
</project>